### ISSUE TITLE
"apply_stroke" Error

### ISSUE THREAD

**Issue by merdem14** [aaronsmithtv/hpaint#1]
Hi, first of all, thanks for the awesome hda.
I opened the example hip file and installed the hda, after invoking the tool I left clicked and I got this error. I tested in 19 and 19.5 versions but did'nt fix the error.

![image](https://user-images.githubusercontent.com/84456102/215651805-d68f2925-b8db-4e82-891d-c28ca79745d4.png)

**Comment by aaronsmithtv** [comment]
Hey bud, looks like you're using an old version! [Can you try hpaint v1.2](https://github.com/aaronsmithtv/hpaint/releases/tag/v1.2) and see if that works?

**Comment by merdem14** [comment]
That fixed it. Looks like [Sidefx's download link](https://www.sidefx.com/tech-art-challenge-2021/) points to an old version. Thanks for the quick response.
