### ISSUE TITLE
AttributeError: 'PrimGroup' object has no attribute 'primCount' in 19.5.303

### ISSUE THREAD

**Issue by aaronsmithtv** [aaronsmithtv/hpaint#4]
It seems that there is currently an issue with the `PrimGroup` object in 19.5.303 where it does not have the `primCount` method:

`AttributeError: 'PrimGroup' object has no attribute 'primCount' in 19.5.303`

Please use 19.5.368 for the time being, thanks! :)

**Comment by HakunanMatatat** [comment]
dear developer, can't draw in 19.5.435, no action, no sugestion. 

I have no idea, what's wrong?
