### ISSUE TITLE
Cannot load example file

### ISSUE THREAD

**Issue by taec12** [aaronsmithtv/hpaint#5]
Thanks for the great HDA!I enjoy using it very much!

I installed HDA and downloaded your sample file from Github, but I get an error.
The Hpaint SOP comes up, but I get an error when I load it.

What should I do?
![スクリーンショット 2023-11-19 225824](https://github.com/aaronsmithtv/hpaint/assets/108446619/c53b4bb1-a493-4c24-93dd-015df705252c)

**Comment by aaronsmithtv** [comment]
Hey @taec12 thanks for submitting this issue! It looks like the HPaint HDA version in the example hasn't been updated from 1.2 to 2.0, so I think you will have to download and install 1.2 in order to get it working. I'll have a look at updating the examples :)

**Comment by taec12** [comment]
Thank you for your quick response!!

I'll try to get the same version of HPaint.
I would be very happy if you could upgrade examples as well!

Thanks for developing this interesting HDA :))
